-- Generated by node scripts/build-bootstrap-sql.mjs. Do not edit this file.
-- Source of truth: roster-server/migrations/*.sql (24 migrations).
-- Requires the existing Supabase anon, authenticated and service_role roles.
-- Ledger guards avoid replaying old constraints over newer, populated A2 data.
CREATE SCHEMA IF NOT EXISTS a2;
SET search_path TO a2;
BEGIN;
CREATE TABLE IF NOT EXISTS a2._bootstrap_migrations (
  name text PRIMARY KEY,
  digest text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE a2._bootstrap_migrations ENABLE ROW LEVEL SECURITY;

-- 0001_roster.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0001_roster.sql' AND digest <> '44ce6476391daaed8611ef4225d3958b8058f2113896b51ba34c2ace14255fb7') THEN
    RAISE EXCEPTION 'Applied migration 0001_roster.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0001_roster.sql') THEN
-- 0001_roster.sql — Gradebook Phase 0. Apply to the shared Supabase project, schema a2
-- (project selected via deployment environment; §6.1 revised 2026-05-17 / D-G). Creates ONLY roster + roster_alias
-- (idempotent, RLS on those two only) — NEVER ALTER or touch existing tables in this shared project.
-- gen_random_uuid() is built into PostgreSQL 13+; no shared extension changes.

create table if not exists roster (
  student_id     uuid primary key default gen_random_uuid(),
  real_name      text not null,
  section        text not null,
  login_username text not null unique,
  password_hash  text not null,
  email          text,
  status         text not null default 'active' check (status in ('active','archived')),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists roster_alias (
  alias_id   uuid primary key default gen_random_uuid(),
  student_id uuid not null references roster(student_id) on delete cascade,
  source     text not null check (source in ('worksheet','studyguide','roadmap')),
  legacy_key text not null,
  created_at timestamptz not null default now(),
  unique (source, legacy_key)
);

create index if not exists roster_section_idx on roster(section);
create index if not exists roster_alias_student_idx on roster_alias(student_id);

-- updated_at trigger
create or replace function roster_touch_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql SET search_path TO a2;
drop trigger if exists roster_set_updated_at on roster;
create trigger roster_set_updated_at before update on roster
  for each row execute function roster_touch_updated_at();

-- RLS: enabled with NO policies => only the service-role key (which bypasses RLS) can touch these.
alter table roster        enable row level security;
alter table roster_alias  enable row level security;
-- (Intentionally NO create policy statements. Anon/auth roles get zero rows. Spec §7.1.)
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0001_roster.sql', '44ce6476391daaed8611ef4225d3958b8058f2113896b51ba34c2ace14255fb7');
  END IF;
END;
$migration$;

-- 0002_item_ledger.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0002_item_ledger.sql' AND digest <> 'a8b3dc82c8000a3a9f0b7a0d84e55fb13aa18d1086bc7feea4047ea6ee68d489') THEN
    RAISE EXCEPTION 'Applied migration 0002_item_ledger.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0002_item_ledger.sql') THEN
-- 0002_item_ledger.sql — Gradebook Sprint 1. Apply to the shared Supabase project, schema a2
-- (project selected via deployment environment; §6.1 / D-G). Creates ONLY item_ledger — NEVER ALTER/touch existing tables.
create table if not exists item_ledger (
  ledger_id     uuid primary key default gen_random_uuid(),
  student_id    uuid not null references roster(student_id) on delete cascade,
  source        text not null check (source in ('worksheet','frq','curriculum_quiz')),
  item_id       text not null,
  unit          text,
  topic         text,
  skill         text,
  response      jsonb,
  score         numeric,
  evidence_tier text not null default 'practice' check (evidence_tier in ('practice','proctored')),
  attempt       int  not null default 1,
  recorded_at   timestamptz not null default now(),
  graded_at     timestamptz,
  unique (student_id, source, item_id, attempt)
);
create index if not exists item_ledger_student_idx on item_ledger(student_id);
create index if not exists item_ledger_skill_idx   on item_ledger(skill);
create index if not exists item_ledger_unit_idx    on item_ledger(unit);
alter table item_ledger enable row level security;
-- (Intentionally NO policies. Service-role only. Blooket is excluded by spec — no 'blooket' source.)
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0002_item_ledger.sql', 'a8b3dc82c8000a3a9f0b7a0d84e55fb13aa18d1086bc7feea4047ea6ee68d489');
  END IF;
END;
$migration$;

-- 0003_roster_pw.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0003_roster_pw.sql' AND digest <> '5d6df8fc0152c42c1b28d36373d6491134a9dc42304443ffcca94f9861a1b87a') THEN
    RAISE EXCEPTION 'Applied migration 0003_roster_pw.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0003_roster_pw.sql') THEN
-- 0003_roster_pw.sql — Gradebook teacher-tools TR1. Apply to the shared Supabase project, schema a2 (project selected via deployment environment). ADDITIVE ONLY: adds two columns to the
-- existing `roster` table. NEVER ALTER or touch any other table in this shared project.
--
-- Sanity check first (optional): the two columns should not already exist.
--   select column_name from information_schema.columns
--   where table_name='roster' and column_name in ('password_cipher','must_change_password');
--
-- password_cipher       : AES-256-GCM blob of the CURRENT password (teacher login-recovery).
--                          Readable only with ROSTER_PW_ENC_KEY (Railway env, server-only).
-- must_change_password  : student must change the default password on first sign-in.
--                          Existing rows inherit TRUE (acceptable; real cohort not yet enrolled,
--                          SMOKETEST rows are removed by the existing cleanup chore).

alter table roster add column if not exists password_cipher text;
alter table roster add column if not exists must_change_password boolean not null default true;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0003_roster_pw.sql', '5d6df8fc0152c42c1b28d36373d6491134a9dc42304443ffcca94f9861a1b87a');
  END IF;
END;
$migration$;

-- 0004_remediation_assignment.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0004_remediation_assignment.sql' AND digest <> 'f797ee82853085e29a3796400d778465eac5df8a283b87f77500dcde00e60922') THEN
    RAISE EXCEPTION 'Applied migration 0004_remediation_assignment.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0004_remediation_assignment.sql') THEN
-- 0004_remediation_assignment.sql — Gradebook Phase 4b. Apply to the
-- shared Supabase project, schema a2 (project selected via deployment environment; §6.1 / D-G).
-- Creates ONLY remediation_assignment + its indexes — NEVER ALTER an existing
-- table. Shared-project discipline (same posture as 0001_roster.sql and
-- 0002_item_ledger.sql).
--
-- Schema mirrors GRADEBOOK_GRADING_SPEC.md §6 (record + retake gate). RLS is
-- enabled with zero policies — service-role only access via roster-server.
--
-- Until this migration is run, the Phase-4b roster-server endpoints respond
-- with 503 {ok:false, error:"remediation table not yet provisioned"}; the
-- rest of the service stays up. See GRADEBOOK_PHASE4B_BUILD.md §1.

create table if not exists remediation_assignment (
  assignment_id    uuid primary key default gen_random_uuid(),
  student_id       uuid not null references roster(student_id) on delete cascade,
  unit             text not null,
  skill            text not null,
  source_attempt   text,                                          -- optional ref to an item_ledger row id
  assigned_refs    jsonb not null default '[]'::jsonb,            -- list of items the student is being asked to do
  status           text not null check (status in ('proposed','assigned','completed','waived')) default 'proposed',
  proposed_by      text not null default 'system',
  approved_by      text,                                          -- teacher username/email, set on approve
  assigned_at      timestamptz,                                   -- set on approve (status='assigned')
  completed_at     timestamptz,                                   -- set on complete (status='completed')
  completed_score  numeric,                                       -- optional score on the re-check item
  recheck_item_id  text,                                          -- the item that closed the loop
  unlocks          text,                                          -- the re-check this remediation gates (free-form id/name)
  notes            text,                                          -- optional teacher notes
  created_at       timestamptz not null default now()
);

create index if not exists remediation_student_idx       on remediation_assignment(student_id);
create index if not exists remediation_skill_idx         on remediation_assignment(skill);
create index if not exists remediation_status_idx        on remediation_assignment(status);
create index if not exists remediation_student_skill_idx on remediation_assignment(student_id, skill);

alter table remediation_assignment enable row level security;
-- Intentionally NO policies. Service-role only. Same posture as roster + item_ledger.
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0004_remediation_assignment.sql', 'f797ee82853085e29a3796400d778465eac5df8a283b87f77500dcde00e60922');
  END IF;
END;
$migration$;

-- 0005_roster_role.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0005_roster_role.sql' AND digest <> '0dd12af99f34d14c69787ddfff4a1fad0e866c292c7bad1dfa36f8f627cfc682') THEN
    RAISE EXCEPTION 'Applied migration 0005_roster_role.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0005_roster_role.sql') THEN
-- 0005_roster_role.sql -- Connected Teacher Auth (TEACHER_AUTH_BUILD.md).
--
-- Adds a `role` column to the roster table so a teacher's own roster
-- account can authorize the teacher-gated endpoints via its session
-- token. The x-teacher-secret stays as a break-glass fallback.
--
-- Additive + idempotent. Run by hand in the curriculum_render Supabase
-- SQL editor (same as migration 0004). Until this runs, roster-server
-- degrades safely: the token-based teacher path resolves every account
-- to 'student', so teachers keep using x-teacher-secret -- no lockout.

ALTER TABLE roster
  ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'student';

-- Constrain to the two valid values. Guarded so a re-run does not error.
DO $$ BEGIN
  ALTER TABLE roster ADD CONSTRAINT roster_role_chk
    CHECK (role IN ('student','teacher'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Mark the teacher account. ADJUST the username below if the teacher's
-- roster account is not 'date_tiger'.
UPDATE roster SET role = 'teacher' WHERE login_username = 'date_tiger';
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0005_roster_role.sql', '0dd12af99f34d14c69787ddfff4a1fad0e866c292c7bad1dfa36f8f627cfc682');
  END IF;
END;
$migration$;

-- 0006_roster_sprite_hue.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0006_roster_sprite_hue.sql' AND digest <> '1c97ccb55a7ef069a908ed946366a450f7dfd8dc9340e324cfc0cc188c16e886') THEN
    RAISE EXCEPTION 'Applied migration 0006_roster_sprite_hue.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0006_roster_sprite_hue.sql') THEN
-- 0006_roster_sprite_hue.sql -- Live Classroom r3 (LIVE_CLASSROOM_R3_BUILD.md).
--
-- Adds a `sprite_hue` column to the roster table so a student's chosen
-- avatar hue persists cross-app via their roster account. The Live Classroom
-- board reads this via GET /roster/verify (spriteHue field) and writes it
-- via PATCH /roster/:studentId/sprite-hue.
--
-- Additive + idempotent. Run by hand in the curriculum_render Supabase
-- SQL editor (same pattern as migrations 0004 and 0005). Until this runs,
-- roster-server degrades safely: getSpriteHueByStudentId returns null and
-- the PATCH route responds 503 "sprite_hue not provisioned" -- no lockout.

ALTER TABLE roster
  ADD COLUMN IF NOT EXISTS sprite_hue integer;

-- Constrain to valid hue range (0-359) or NULL. Guarded so a re-run does not error.
DO $$ BEGIN
  ALTER TABLE roster ADD CONSTRAINT roster_sprite_hue_chk
    CHECK (sprite_hue IS NULL OR sprite_hue BETWEEN 0 AND 359);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0006_roster_sprite_hue.sql', '1c97ccb55a7ef069a908ed946366a450f7dfd8dc9340e324cfc0cc188c16e886');
  END IF;
END;
$migration$;

-- 0008_nudges_log.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0008_nudges_log.sql' AND digest <> '5c6ff785053c6ba791f705188df464bdc16c0369fe1455c3b0cd0cfcb9d41de6') THEN
    RAISE EXCEPTION 'Applied migration 0008_nudges_log.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0008_nudges_log.sql') THEN
-- 0008_nudges_log.sql -- nudges_log persistence (Phase 3 of
-- TEACHER_STUDENT_CONSOLE_SPEC.md). One row per teacher -> student
-- nudge AND per student -> teacher reply. Idempotent.

create table if not exists nudges_log (
  id                 bigserial primary key,
  nudge_id           text not null,
  parent_nudge_id    text,
  sender_username    text not null,
  recipient_username text not null,
  text               text not null check (char_length(text) <= 280),
  direction          text not null check (direction in ('teacher', 'student')),
  section            text,
  created_at         timestamptz not null default now(),
  delivered_at       timestamptz
);

create index if not exists nudges_log_nudge_id_idx on nudges_log (nudge_id);
create index if not exists nudges_log_recipient_section_idx on nudges_log (recipient_username, section, created_at desc);
create index if not exists nudges_log_sender_section_idx on nudges_log (sender_username, section, created_at desc);
create index if not exists nudges_log_parent_idx on nudges_log (parent_nudge_id) where parent_nudge_id is not null;

alter table nudges_log enable row level security;
-- Intentionally NO policies. Service-role only (mirrors 0007 + 0004 pattern).
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0008_nudges_log.sql', '5c6ff785053c6ba791f705188df464bdc16c0369fe1455c3b0cd0cfcb9d41de6');
  END IF;
END;
$migration$;

-- 0009_lesson_unlock.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0009_lesson_unlock.sql' AND digest <> '591a130cfd7c6c4190e477e1388bd245c139655c9d4e764da619fc7138f822a7') THEN
    RAISE EXCEPTION 'Applied migration 0009_lesson_unlock.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0009_lesson_unlock.sql') THEN
-- 0009_lesson_unlock.sql -- lesson_unlock persistence (Phase 5 of
-- TEACHER_STUDENT_CONSOLE_SPEC.md). Records teacher overrides of the
-- sequential lesson gate. Sticky (status='active' persists across
-- sessions). One row per (student, lesson) -- UNIQUE constraint.
-- Idempotent.

create table if not exists lesson_unlock (
  id                 bigserial primary key,
  student_username   text not null,
  lesson_key         text not null,
  unlocked_by        text not null,
  unlocked_at        timestamptz not null default now(),
  reason             text,
  status             text not null default 'active' check (status in ('active', 'revoked')),
  unique (student_username, lesson_key)
);

create index if not exists lesson_unlock_student_idx on lesson_unlock (student_username) where status = 'active';
create index if not exists lesson_unlock_lesson_idx on lesson_unlock (lesson_key);

alter table lesson_unlock enable row level security;
-- Intentionally NO policies. Service-role only (mirrors 0007 + 0008).
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0009_lesson_unlock.sql', '591a130cfd7c6c4190e477e1388bd245c139655c9d4e764da619fc7138f822a7');
  END IF;
END;
$migration$;

-- 0010_schoology_sync.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0010_schoology_sync.sql' AND digest <> '1c73b60ee0df300254ecdc196c59b16faba7b2da6405c36df92c02adeb2da19d') THEN
    RAISE EXCEPTION 'Applied migration 0010_schoology_sync.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0010_schoology_sync.sql') THEN
-- 0010_schoology_sync: Schoology grade-sync tables (assignments, delta tracking, run log).

-- One row per Schoology gradebook column (assignment).
create table if not exists schoology_assignment (
  id                       uuid primary key default gen_random_uuid(),
  section                  text not null,
  lesson_key               text not null,
  kind                     text not null check (kind in ('lesson','test','progress_check')),
  title                    text not null,
  points                   integer not null default 100,
  due_date                 date,
  category                 text,
  schoology_assignment_id  text,
  schoology_course_id      text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  unique (section, lesson_key)
);

-- Delta tracking: what value was last pushed to Schoology for each (student, assignment).
create table if not exists schoology_grade_sync (
  student_id               text not null,
  assignment_id            uuid not null references schoology_assignment(id) on delete cascade,
  last_synced_value        numeric,
  last_synced_at           timestamptz,
  last_attempted_at        timestamptz,
  last_error               text,
  primary key (student_id, assignment_id)
);

-- One row per sync run.
create table if not exists schoology_sync_log (
  id                       uuid primary key default gen_random_uuid(),
  run_id                   text not null,
  section                  text,
  started_at               timestamptz not null,
  finished_at              timestamptz,
  success                  boolean,
  assignments_created      integer default 0,
  grades_pushed            integer default 0,
  grades_skipped           integer default 0,
  errors_json              jsonb,
  notes                    text,
  created_at               timestamptz not null default now()
);

create index if not exists schoology_sync_log_finished_idx on schoology_sync_log(finished_at desc);

alter table schoology_assignment enable row level security;
alter table schoology_grade_sync enable row level security;
alter table schoology_sync_log enable row level security;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0010_schoology_sync.sql', '1c73b60ee0df300254ecdc196c59b16faba7b2da6405c36df92c02adeb2da19d');
  END IF;
END;
$migration$;

-- 0012_roster_schoology_uid.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0012_roster_schoology_uid.sql' AND digest <> '0bf274000419d79b17501c7eed822a064a3995e86a62008e4fbad055cb6525fc') THEN
    RAISE EXCEPTION 'Applied migration 0012_roster_schoology_uid.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0012_roster_schoology_uid.sql') THEN
-- 0012_roster_schoology_uid: add the schoology_uid bridge column to roster.
-- Maps a roster student to their Schoology user id so the grade-sync producer
-- (tools/build_schoology_fixture.py) can key the fixture by Schoology uid
-- directly, instead of a hand-authored --uid-map. GRADE_PIPELINE_E2E_SPEC.md P4b.
--
-- Additive + idempotent. Run on the shared curriculum_render Supabase. NEVER
-- ALTER or touch any other table in this shared project.
alter table roster add column if not exists schoology_uid text;

-- One Schoology account maps to at most one roster row. Partial unique index
-- (nulls ignored) blocks two students sharing a uid; many NULLs are allowed.
create unique index if not exists roster_schoology_uid_key
  on roster (schoology_uid) where schoology_uid is not null;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0012_roster_schoology_uid.sql', '0bf274000419d79b17501c7eed822a064a3995e86a62008e4fbad055cb6525fc');
  END IF;
END;
$migration$;

-- 0013_item_ledger_blooket_source.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0013_item_ledger_blooket_source.sql' AND digest <> '4a12cf765dc2b142f143c813ba91e0781f8405a357d1f13bba9444adf81f2f48') THEN
    RAISE EXCEPTION 'Applied migration 0013_item_ledger_blooket_source.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0013_item_ledger_blooket_source.sql') THEN
-- 0013_item_ledger_blooket_source: allow source='blooket' (per-lesson Blooket
-- warm-up rows) in item_ledger.
--
-- USER-RUN (run on the shared Supabase, like 0011). Additive: this widens the
-- source CHECK to admit the new Blooket track of Grading Model v3 (10% of Work,
-- renormalized). The teacher endpoint POST /class/blooket writes source='blooket'
-- rows; before this migration runs Postgres REJECTS them (check_violation), and
-- the endpoint reports 503 "blooket source not provisioned" so the service stays
-- up and no missing blooket is ever counted as 0.
--
-- Mirror of 0011: drop + re-add the source CHECK with the extra value.
--
--
-- If your constraint has a non-default name, find it with `\d item_ledger` (psql)
-- and adjust the DROP below. The default for an inline column CHECK is
-- <table>_<column>_check = item_ledger_source_check.

alter table item_ledger drop constraint if exists item_ledger_source_check;

alter table item_ledger add constraint item_ledger_source_check
  check (source in ('worksheet','frq','curriculum_quiz','blooket'));
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0013_item_ledger_blooket_source.sql', '4a12cf765dc2b142f143c813ba91e0781f8405a357d1f13bba9444adf81f2f48');
  END IF;
END;
$migration$;

-- 0014_item_ledger_quiz_exception.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0014_item_ledger_quiz_exception.sql' AND digest <> '334d9abf922a3a611972bf7916d153c60dca0369dc7525c9372551716f4604e5') THEN
    RAISE EXCEPTION 'Applied migration 0014_item_ledger_quiz_exception.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0014_item_ledger_quiz_exception.sql') THEN
-- 0014_item_ledger_quiz_exception: allow source='quiz_exception' (AI-granted
-- "discuss your answer" exceptions that flip a wrong quiz item to correct) in
-- item_ledger.
--
-- USER-RUN (run on the shared Supabase, like 0011 / 0013). Additive: widens the
-- source CHECK to admit exception rows. The cr quiz "Discuss with AI" flow writes
-- a source='quiz_exception' row (item_id = `<baseItemId>#exc`) only after the AI
-- grants the appeal; the grade engine ORs that into the base item's correctness.
-- Before this migration runs Postgres REJECTS the rows (check_violation) and the
-- fire-and-forget feeder no-ops, so no exception is ever silently lost or counted.
--
-- The exception row uses a DISTINCT `#exc` item_id on purpose: latestPerItem
-- dedupes by item_id alone, so reusing the quiz item's id would replace the quiz
-- row. The engine strips `#exc` to find the base item it forgives.
--
-- Mirror of 0011 / 0013: drop + re-add the source CHECK with the extra value.
-- Default inline-CHECK name is item_ledger_source_check.

alter table item_ledger drop constraint if exists item_ledger_source_check;

alter table item_ledger add constraint item_ledger_source_check
  check (source in ('worksheet','frq','curriculum_quiz','blooket','quiz_exception'));
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0014_item_ledger_quiz_exception.sql', '334d9abf922a3a611972bf7916d153c60dca0369dc7525c9372551716f4604e5');
  END IF;
END;
$migration$;

-- 0015_item_ledger_quiz_review.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0015_item_ledger_quiz_review.sql' AND digest <> '8b10b47d89fc0e2b6069138a15e5bba5a2af91b563c54afab510f1bd869a7988') THEN
    RAISE EXCEPTION 'Applied migration 0015_item_ledger_quiz_review.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0015_item_ledger_quiz_review.sql') THEN
-- 0015_item_ledger_quiz_review: allow source='quiz_review' (AI-review partial
-- credit for quiz items) in item_ledger.
--
-- USER-RUN (run on the shared Supabase, like 0011/0013/0014). Additive: widens
-- the source CHECK. A quiz_review row (item_id '<baseItemId>#rev', score = earned
-- credit 1.0 / 0.667 / 0.333) is written by cr when an AI review/appeal completes:
--   E / exception-granted -> 1.0,  P -> 0.667,  I (engaged the review) -> 0.333.
-- The grade engine takes max(answer-key correct ? 1 : 0, reviewCredit) per item
-- and scores Q = sum(credit) / total. This GENERALIZES the s125 quiz_exception
-- (which was E-only, 1.0); quiz_exception stays in the CHECK for safety and the
-- engine still reads it as credit 1.0.
--
-- Distinct '#rev' item id is REQUIRED (latestPerItem dedupes by item_id, so it
-- must not collide with the quiz row). Before this migration runs Postgres
-- rejects the rows and the fire-and-forget feeder no-ops.
--
-- Mirror of 0011/0013/0014: drop + re-add the source CHECK with the extra value.

alter table item_ledger drop constraint if exists item_ledger_source_check;

alter table item_ledger add constraint item_ledger_source_check
  check (source in ('worksheet','frq','curriculum_quiz','blooket','quiz_exception','quiz_review'));
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0015_item_ledger_quiz_review.sql', '8b10b47d89fc0e2b6069138a15e5bba5a2af91b563c54afab510f1bd869a7988');
  END IF;
END;
$migration$;

-- 0018_item_ledger_receipt.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0018_item_ledger_receipt.sql' AND digest <> 'f17cd77c2260d5322af30d59d47e82b2d755c0b5d09150cf64d0653029e88b18') THEN
    RAISE EXCEPTION 'Applied migration 0018_item_ledger_receipt.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0018_item_ledger_receipt.sql') THEN
-- 0018_item_ledger_receipt: persist signed ledger receipts for durable replay.
--
-- USER-RUN (run on the shared Supabase, like 0011/0013/0014/0015/0016 -- never
-- auto-run). Additive: adds nullable receipt columns to item_ledger.
--
-- Until this migration runs, receipt persistence silently no-ops: grade writes
-- still succeed, signed receipts are still returned in-band, and GET
-- /ledger/student returns rows without receipt fields.

alter table item_ledger add column if not exists receipt_id text;
alter table item_ledger add column if not exists receipt_compact text;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0018_item_ledger_receipt.sql', 'f17cd77c2260d5322af30d59d47e82b2d755c0b5d09150cf64d0653029e88b18');
  END IF;
END;
$migration$;

-- 0025_review_marks.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0025_review_marks.sql' AND digest <> 'd9e61ef87a902546f0cc72aafbe38e83e600287cbca6111db702ba3681641480') THEN
    RAISE EXCEPTION 'Applied migration 0025_review_marks.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0025_review_marks.sql') THEN
create table if not exists review_marks (
  review_id        uuid primary key default gen_random_uuid(),
  ledger_id        uuid not null references item_ledger(ledger_id) on delete cascade,
  student_id       uuid not null,
  teacher_username text not null,
  seen_at          timestamptz not null default now(),
  comment          text,                            -- nullable; route caps <= 500 chars
  receipt_id       text,                            -- signed t:'review' receipt (best-effort persist)
  receipt_compact  text,
  updated_at       timestamptz not null default now(),
  unique (ledger_id)
);
create index if not exists review_marks_student_idx on review_marks (student_id);
create index if not exists review_marks_seen_idx     on review_marks (seen_at);

alter table review_marks enable row level security;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0025_review_marks.sql', 'd9e61ef87a902546f0cc72aafbe38e83e600287cbca6111db702ba3681641480');
  END IF;
END;
$migration$;

-- 0026_trusted_issuers.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0026_trusted_issuers.sql' AND digest <> '52b49907807673ddcd561bda64f92a85554f7ee17ec0e7717bfb88272f0e4fdc') THEN
    RAISE EXCEPTION 'Applied migration 0026_trusted_issuers.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0026_trusted_issuers.sql') THEN
-- 0026_trusted_issuers: persisted issuer-key trust set (ANDROID Phase 4 §3B).
--
-- USER-RUN (run on the shared Supabase, like 0011/0013/0014/0015/0016/0018/0025 --
-- never auto-run). Additive + idempotent.
--
-- A teacher DEVICE generates its own Ed25519 key (hardware-wrapped, biometric-gated)
-- and registers its PUBLIC key here via POST /receipts/trusted-issuers, so receipts
-- that device signs verify everywhere. getTrustedIssuerPubkeys() merges these rows
-- into the trust set (with the current signer + RETIRED_ISSUER_PUBKEYS env), and
-- GET /receipts/issuer advertises the full set to every client.
--
-- Until this migration runs, POST /receipts/trusted-issuers returns 503 and the
-- trust set falls back to the current key + the RETIRED_ISSUER_PUBKEYS env (so the
-- env path keeps working as a manual fallback).

create table if not exists trusted_issuers (
  pubkey     text primary key,   -- base64url Ed25519 public-key x (43 chars)
  label      text,               -- human note, e.g. "Teacher Pixel 8"
  revoked    boolean not null default false,
  created_at timestamptz not null default now()
);

-- Service-role (the server) bypasses RLS; no anon access. Mirrors 0025.
alter table trusted_issuers enable row level security;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0026_trusted_issuers.sql', '52b49907807673ddcd561bda64f92a85554f7ee17ec0e7717bfb88272f0e4fdc');
  END IF;
END;
$migration$;

-- 0027_student_keys.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0027_student_keys.sql' AND digest <> '06add5f8c5088c5780ab269e30f5d0967007a395f2893617f30b52518bcc60b3') THEN
    RAISE EXCEPTION 'Applied migration 0027_student_keys.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0027_student_keys.sql') THEN
-- 0027_student_keys: the STUDENT trust set for the offline-grading mesh
-- (OFFLINE_GRADING_MESH_SPEC.md §0.1-0.3). USER-RUN, additive, idempotent.
--
-- Students self-sign raw SUBMISSIONS (never grades) with a device Ed25519 key;
-- this table is the authenticated pubkey→student binding (§0.2) plus revocation
-- (§0.3). It deliberately mirrors 0026_trusted_issuers with two hard differences:
--   1. It is a SEPARATE table from trusted_issuers — the grades trust set and the
--      student trust set are never merged (§0.1c). A pubkey in one must never
--      appear in the other (enforced at the route layer).
--   2. Revocation is TERMINAL: re-registering a revoked pubkey must NOT un-revoke
--      it (a lost/stolen key signs as the student forever if it can come back).
--      trusted_issuers' upsert-un-revoke behavior is acceptable for teacher-gated
--      issuer keys, catastrophic for a fleet of student keys.
--
-- One-sid-per-pubkey: pubkey is the PK; a key can never re-bind to a different
-- student (§0.5). One student MAY hold several keys over time (new device → new
-- key; old keys stay so old submissions keep verifying, unless revoked).
--
-- Until this runs, /student-keys* routes return 503 and the mesh submissions
-- lane stays inert (no student trust set to verify against).

create table if not exists student_keys (
  pubkey     text primary key,   -- base64url Ed25519 public-key x (43 chars)
  student_id uuid not null references roster(student_id) on delete cascade,
  label      text,               -- human note, e.g. "Pixel 3 (app)"
  revoked    boolean not null default false,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists student_keys_student_idx on student_keys (student_id);

-- Service-role bypasses RLS; no anon access. Mirrors 0025/0026.
alter table student_keys enable row level security;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0027_student_keys.sql', '06add5f8c5088c5780ab269e30f5d0967007a395f2893617f30b52518bcc60b3');
  END IF;
END;
$migration$;

-- 0028_submission_archive.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0028_submission_archive.sql' AND digest <> '4a149ffad9d3321d204250274c1ad12645a4d731f86ca6f09e979da32924eea5') THEN
    RAISE EXCEPTION 'Applied migration 0028_submission_archive.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0028_submission_archive.sql') THEN
-- 0028_submission_archive: the offline-grading-mesh hub reconcile (Phase 4).
-- OFFLINE_GRADING_MESH_SPEC.md §0.10, §4. USER-RUN, additive, idempotent.
--
-- When a device with internet reaches the server, it uploads the raw student
-- SUBMISSIONS it has gossiped (self-signed, t:'submission') so they're durable off
-- the mesh and auditable. This table is APPEND-ONLY and content-addressed by the
-- submission's receipt_id — re-uploading the same submission is a no-op (idempotent).
--
-- CRITICAL (§0.10): archiving is DECOUPLED from grading. This table is NOT item_ledger
-- and nothing here ever writes a score — so the server can NEVER re-grade a submission
-- that already carries a teacher grade, nor mint a competing score. Teacher-signed
-- grades reach the ledger through the EXISTING /admin/restore path (the teacher device
-- key is a trusted issuer); the archive is purely the raw-work record.
--
-- The server verifies each submission's STUDENT signature (against student_keys from
-- migration 0027) before storing, so a peer can't inject a fake submission.
--
-- Until this runs, POST/GET /submissions/archive 503 (table absent).

create table if not exists submission_archive (
  receipt_id      text primary key,          -- content address (sha256 of the signed payload)
  student_id      uuid not null references roster(student_id) on delete cascade,
  source          text not null,
  item_id         text not null,
  response        jsonb,
  attempt         int not null default 1,
  recorded_at     timestamptz,               -- the student's signed submission ts (display-only, §0.11)
  receipt_compact text not null,             -- the full self-signed receipt (re-verifiable)
  archived_at     timestamptz not null default now()
);

create index if not exists submission_archive_student_idx on submission_archive (student_id);
create index if not exists submission_archive_item_idx    on submission_archive (item_id);

-- Defense-in-depth RLS (service-role bypasses); mirrors 0025/0026/0027.
alter table submission_archive enable row level security;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0028_submission_archive.sql', '4a149ffad9d3321d204250274c1ad12645a4d731f86ca6f09e979da32924eea5');
  END IF;
END;
$migration$;

-- 0030_quarter_grade_snapshot.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0030_quarter_grade_snapshot.sql' AND digest <> '5ea5124967196f4b8b09157801a0578130b3ca30034adf75f56904707d11d9f8') THEN
    RAISE EXCEPTION 'Applied migration 0030_quarter_grade_snapshot.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0030_quarter_grade_snapshot.sql') THEN
-- 0030_quarter_grade_snapshot: freeze a student's quarter grade at teacher-run
-- quarter close (PC makeup [D] freeze/delta). The snapshot is the AUTHORITATIVE
-- closed-quarter record — the teacher enters it into Schoology at close; the live
-- engine keeps recomputing, and post-close improvements surface as BONUS DELTAS
-- (current - frozen). Best-wins-at-write (Phase 2 /pc submit) guarantees the live
-- grade only ever RISES post-close, so a delta is always a positive extra-credit
-- candidate, never a drop the freeze has to shield against.
--
-- Idempotent close: PK(student_id, quarter) + INSERT ... ON CONFLICT DO NOTHING
-- (the FIRST close wins — a frozen grade is immutable; re-closing only snapshots
-- students not yet frozen). /class/quarter/* return 503 until this is applied.

create table if not exists quarter_grade_snapshot (
  student_id      text not null,
  quarter         text not null check (quarter in ('Q1','Q2','Q3','Q4')),
  login_username  text,                 -- for teacher-facing display
  frozen_grade    numeric,              -- the quarterGrade at close (0..100, or null = nothing due)
  frozen_pc_avg   numeric,              -- the PC-track avg at close (detail)
  frozen_work_avg numeric,              -- the Work-track avg at close (detail)
  closed_by       text,                 -- acting teacher (best-effort)
  frozen_at       timestamptz not null default now(),
  primary key (student_id, quarter)
);

-- Service-role only (same policy as the ledger): the roster server holds
-- the service key; no anon/authenticated policies are defined.
alter table quarter_grade_snapshot enable row level security;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0030_quarter_grade_snapshot.sql', '5ea5124967196f4b8b09157801a0578130b3ca30034adf75f56904707d11d9f8');
  END IF;
END;
$migration$;

-- 0031_frq_tickets.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0031_frq_tickets.sql' AND digest <> '0d2f383dc43982434d9fb0affcb8323af67ba7d860ee120ee88ac9fe9a7a0bf8') THEN
    RAISE EXCEPTION 'Applied migration 0031_frq_tickets.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0031_frq_tickets.sql') THEN
-- 0031_frq_tickets.sql -- turn an existing FRQ ledger row into a durable,
-- leased grade ticket without rewriting item_ledger.
--
-- Expected lock profile: on PostgreSQL 11+, nullable columns and columns with
-- constant defaults are metadata-only ADD COLUMN operations. The single ALTER
-- acquires ACCESS EXCLUSIVE once. The two partial index builds below acquire a
-- SHARE lock; at the current item_ledger row count each build is expected to take
-- seconds. Operators who cannot accept that lock should use the commented
-- non-transactional CONCURRENTLY alternative below instead of the two ordinary
-- CREATE INDEX statements. No statement in this migration rewrites the table.

alter table item_ledger
  add column if not exists frq_response_version bigint not null default 0,
  add column if not exists frq_response_hash text,
  add column if not exists frq_ready_at timestamptz,
  add column if not exists frq_claim_token uuid,
  add column if not exists frq_claim_owner text,
  add column if not exists frq_claimed_until timestamptz,
  add column if not exists frq_retry_count int not null default 0,
  add column if not exists frq_next_attempt_at timestamptz,
  add column if not exists frq_last_error text,
  add column if not exists frq_result jsonb,
  add column if not exists frq_rubric_version text,
  add column if not exists frq_appeal_count int not null default 0,
  add column if not exists frq_appeal_pending jsonb,
  add column if not exists frq_last_appeal jsonb;

-- WHY: frq_ready_at + ledger_id provide the claim query's due-time order and
-- stable tie-breaker. The trailing retry/lease columns cover its remaining time
-- eligibility checks before the bounded set of rows is visited and locked. The
-- immutable partial predicate keeps drafts and non-FRQ rows out of the index.
create index if not exists item_ledger_frq_claim_scan_idx
  on item_ledger (frq_ready_at, ledger_id, frq_next_attempt_at, frq_claimed_until)
  where source = 'frq'
    and score is null
    and response is not null
    and jsonb_typeof(response) = 'string'
    and char_length(response #>> '{}') >= 20
    and frq_ready_at is not null;

-- WHY: appeals use recorded_at for their due-time order and are absent from the
-- initial-work partition. The remaining keys cover the tie-breaker and time gates.
create index if not exists item_ledger_frq_appeal_scan_idx
  on item_ledger (recorded_at, ledger_id, frq_next_attempt_at, frq_claimed_until)
  where source = 'frq' and score is not null and frq_appeal_pending is not null;

-- Non-transactional alternative for a larger production table (do not run these
-- inside a migration transaction; comment out the two ordinary builds above):
--   -- DROP also removes an invalid index left by an interrupted prior build.
--   drop index concurrently if exists item_ledger_frq_claim_scan_idx;
--   create index concurrently item_ledger_frq_claim_scan_idx
--     on item_ledger (frq_ready_at, ledger_id, frq_next_attempt_at, frq_claimed_until)
--     where source = 'frq' and score is null and response is not null
--       and jsonb_typeof(response) = 'string'
--       and char_length(response #>> '{}') >= 20 and frq_ready_at is not null;
--   drop index concurrently if exists item_ledger_frq_appeal_scan_idx;
--   create index concurrently item_ledger_frq_appeal_scan_idx
--     on item_ledger (recorded_at, ledger_id, frq_next_attempt_at, frq_claimed_until)
--     where source = 'frq' and score is not null and frq_appeal_pending is not null;

-- Atomically create or refresh the unique (student, frq, item, attempt=1) ticket.
-- ON CONFLICT takes the same row lock an explicit SELECT FOR UPDATE would take.
-- A graded row is deliberately immutable here: score and its bound response/hash
-- survive cached drafts and OfflineQueue replay.
create or replace function record_frq_draft(
  p_student_id uuid,
  p_item_id text,
  p_response text,
  p_response_hash text,
  p_ready_at timestamptz
)
returns table (
  ledger_id uuid,
  status text,
  response_version bigint
)
language sql SET search_path TO a2
as $$
  with upserted as (
    insert into item_ledger (
      student_id,
      source,
      item_id,
      response,
      score,
      attempt,
      frq_response_version,
      frq_response_hash,
      frq_ready_at
    )
    values (
      p_student_id,
      'frq',
      p_item_id,
      to_jsonb(p_response),
      null,
      1,
      1,
      p_response_hash,
      p_ready_at
    )
    on conflict (student_id, source, item_id, attempt) do update
    set
      response = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then excluded.response
        else item_ledger.response
      end,
      frq_response_version = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then item_ledger.frq_response_version + 1
        else item_ledger.frq_response_version
      end,
      frq_response_hash = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then excluded.frq_response_hash
        else item_ledger.frq_response_hash
      end,
      -- An identical blur/Done replay may only make work ready sooner. It must
      -- not delay an existing ticket or invalidate a worker grading the same text.
      frq_ready_at = case
        when item_ledger.score is not null then item_ledger.frq_ready_at
        when item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then excluded.frq_ready_at
        else coalesce(
          least(item_ledger.frq_ready_at, excluded.frq_ready_at),
          item_ledger.frq_ready_at,
          excluded.frq_ready_at
        )
      end,
      frq_claim_token = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then null
        else item_ledger.frq_claim_token
      end,
      frq_claim_owner = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then null
        else item_ledger.frq_claim_owner
      end,
      frq_claimed_until = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then null
        else item_ledger.frq_claimed_until
      end,
      frq_retry_count = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then 0
        else item_ledger.frq_retry_count
      end,
      frq_next_attempt_at = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then null
        else item_ledger.frq_next_attempt_at
      end,
      frq_last_error = case
        when item_ledger.score is null
          and item_ledger.frq_response_hash is distinct from excluded.frq_response_hash
          then null
        else item_ledger.frq_last_error
      end
    returning item_ledger.*
  )
  select
    u.ledger_id,
    case
      when u.score is not null then 'graded'
      when u.frq_claimed_until > now() then 'grading'
      when u.frq_next_attempt_at > now() then 'retrying'
      when u.response is null
        or jsonb_typeof(u.response) <> 'string'
        or char_length(u.response #>> '{}') < 20
        or u.frq_ready_at is null then 'draft'
      else 'queued'
    end,
    u.frq_response_version
  from upserted as u;
$$;

-- Claim and return one stable snapshot in one statement. FOR UPDATE SKIP LOCKED
-- is the distributed arbiter: concurrent Railway processes cannot select the
-- same current lease, while an expired lease remains recoverable.
-- Remove the superseded clock-injection overload if an earlier draft of this
-- migration was applied. Production eligibility is always based on the DB clock.
drop function if exists claim_frq_tickets(text, int, bigint, timestamptz);
drop function if exists claim_frq_tickets(text, int, bigint);

create or replace function claim_frq_tickets(
  p_worker text,
  p_limit int,
  p_lease_ms bigint
)
returns table (
  ledger_id uuid,
  student_id uuid,
  item_id text,
  response jsonb,
  frq_response_version bigint,
  frq_response_hash text,
  frq_claim_token uuid,
  frq_retry_count int,
  is_appeal boolean,
  attempt int,
  evidence_tier text,
  score numeric,
  frq_result jsonb,
  frq_appeal_pending jsonb,
  graded_at timestamptz
)
language sql SET search_path TO a2
as $$
  with claim_clock as (
    -- One stable database timestamp drives both eligibility and lease expiry.
    select statement_timestamp() as at
  ),
  candidates as (
    select l.ledger_id
    from item_ledger as l
    cross join claim_clock as clock
    where l.source = 'frq'
      and (l.frq_claimed_until is null or l.frq_claimed_until <= clock.at)
      and (l.frq_next_attempt_at is null or l.frq_next_attempt_at <= clock.at)
      and (
        (
          l.score is null
          and l.response is not null
          and jsonb_typeof(l.response) = 'string'
          and char_length(l.response #>> '{}') >= 20
          and l.frq_ready_at is not null
          and l.frq_ready_at <= clock.at
        )
        or
        (
          l.score is not null
          and l.frq_appeal_pending is not null
        )
      )
    order by
      case when l.score is null then l.frq_ready_at else l.recorded_at end,
      l.ledger_id
    for update of l skip locked
    limit greatest(coalesce(p_limit, 0), 0)
  ),
  claimed as (
    update item_ledger as l
    set
      frq_claim_token = gen_random_uuid(),
      frq_claim_owner = p_worker,
      frq_claimed_until = clock.at
        + least(greatest(coalesce(p_lease_ms, 5000), 5000), 600000)
          * interval '1 millisecond'
    from candidates as c
    cross join claim_clock as clock
    where l.ledger_id = c.ledger_id
    returning l.*
  )
  select
    c.ledger_id,
    c.student_id,
    c.item_id,
    c.response,
    c.frq_response_version,
    c.frq_response_hash,
    c.frq_claim_token,
    c.frq_retry_count,
    c.score is not null and c.frq_appeal_pending is not null,
    c.attempt,
    c.evidence_tier,
    c.score,
    c.frq_result,
    c.frq_appeal_pending,
    c.graded_at
  from claimed as c
  order by c.ledger_id;
$$;

-- Queue an appeal under the same row lock used by apply_frq_verdict. This keeps
-- count, dedup, cooldown, and pending replacement one atomic decision and keeps
-- a live worker claim from consuming a newly replaced request.
-- The revised-text parameter changed the argument list; CREATE OR REPLACE with a
-- different signature would ADD an overload (and make 4-argument calls ambiguous,
-- SQLSTATE 42725), so drop the original signature first. Re-run-safe.
drop function if exists queue_frq_appeal(uuid, text, text, timestamptz);
create or replace function queue_frq_appeal(
  p_student_id uuid,
  p_item_id text,
  p_appeal_text text,
  p_requested_at timestamptz default statement_timestamp(),
  p_revised_text text default null
)
returns table (
  queued boolean,
  appeal_count int,
  reason text
)
language plpgsql SET search_path TO a2
as $$
declare
  v_row item_ledger%rowtype;
  -- p_requested_at remains only for rollout signature compatibility. Security
  -- decisions always use the database statement clock.
  v_now timestamptz := statement_timestamp();
  v_appeal_hash text := md5(regexp_replace(btrim(coalesce(p_appeal_text, '')), '[[:space:]]+', ' ', 'g'));
  v_pending_hash text;
  v_last_hash text;
  v_pending_at timestamptz;
  v_last_at timestamptz;
  v_revised_text text;
begin
  select l.*
    into v_row
    from item_ledger as l
    where l.student_id = p_student_id
      and l.source = 'frq'
      and l.item_id = p_item_id
      and l.attempt = 1
    for update;

  if not found then
    return query select false, 0, 'not_found'::text;
    return;
  end if;
  if v_row.score is null then
    return query select false, v_row.frq_appeal_count, 'not_graded'::text;
    return;
  end if;
  if v_row.frq_appeal_count >= 3 then
    return query select false, v_row.frq_appeal_count, 'limit'::text;
    return;
  end if;
  v_revised_text := case
    when p_revised_text is null then null
    when btrim(p_revised_text) = btrim(coalesce(v_row.response #>> '{}', '')) then null
    else btrim(p_revised_text)
  end;
  v_pending_hash := coalesce(
    v_row.frq_appeal_pending ->> 'hash',
    case when v_row.frq_appeal_pending ->> 'text' is not null
      then md5(regexp_replace(btrim(v_row.frq_appeal_pending ->> 'text'), '[[:space:]]+', ' ', 'g'))
    end
  );
  v_last_hash := v_row.frq_last_appeal ->> 'hash';
  if v_appeal_hash = v_pending_hash or v_appeal_hash = v_last_hash then
    return query select false, v_row.frq_appeal_count, 'duplicate'::text;
    return;
  end if;

  begin
    v_pending_at := nullif(v_row.frq_appeal_pending ->> 'requestedAt', '')::timestamptz;
  exception when others then
    v_pending_at := null;
  end;
  begin
    v_last_at := nullif(v_row.frq_last_appeal ->> 'at', '')::timestamptz;
  exception when others then
    v_last_at := null;
  end;
  if v_row.frq_claimed_until > v_now
    or (v_pending_at is not null and v_pending_at > v_now - interval '60 seconds')
    or (v_last_at is not null and v_last_at > v_now - interval '60 seconds') then
    return query select false, v_row.frq_appeal_count, 'cooldown'::text;
    return;
  end if;

  update item_ledger as l
  set
    frq_appeal_count = l.frq_appeal_count + 1,
    frq_appeal_pending = jsonb_strip_nulls(jsonb_build_object(
      'text', p_appeal_text,
      'hash', v_appeal_hash,
      'requestedAt', v_now,
      'version', l.frq_response_version,
      'revisedText', v_revised_text
    )),
    frq_last_appeal = jsonb_build_object('hash', v_appeal_hash, 'at', v_now),
    frq_claim_token = null,
    frq_claim_owner = null,
    frq_claimed_until = null,
    frq_retry_count = 0,
    frq_next_attempt_at = null,
    frq_last_error = null
  where l.ledger_id = v_row.ledger_id
  returning l.frq_appeal_count into v_row.frq_appeal_count;

  return query select true, v_row.frq_appeal_count, 'queued'::text;
end;
$$;

-- (No four-argument compatibility overload: keeping one would make
-- four-argument calls ambiguous against the five-argument default (42725).
-- The old production signature is dropped above; all callers pass named params.)

-- Apply under a row lock so the version/hash decision, max floor, result write,
-- and lease release serialize with drafts and competing graders. responseHash is
-- accepted as internal envelope metadata in p_result and removed before the
-- student-visible result is stored; response_version remains the required binding
-- for callers using the contracted sanitized result shape without that key.
create or replace function apply_frq_verdict(
  p_ledger_id uuid,
  p_claim_token uuid,
  p_response_version bigint,
  p_score numeric,
  p_result jsonb,
  p_rubric_version text,
  p_graded_at timestamptz,
  p_teacher boolean default false
)
returns table (
  applied boolean,
  stale boolean,
  previous_score numeric,
  score numeric,
  ledger_id uuid
)
language plpgsql SET search_path TO a2
as $$
declare
  v_row item_ledger%rowtype;
  v_expected_hash text;
  v_previous_score numeric;
  v_final_score numeric;
  v_applied boolean;
  v_was_appeal boolean;
  v_hash_matches boolean;
  v_claim_matches boolean;
begin
  -- Invalid model output is not a verdict. In particular, do not release its
  -- lease; the caller must classify the failure with fail_frq_claim.
  if p_score is null or p_score not in (0::numeric, 0.5::numeric, 1::numeric) then
    select l.score
      into v_previous_score
      from item_ledger as l
      where l.ledger_id = p_ledger_id;

    return query
      select false, false, v_previous_score, v_previous_score, p_ledger_id;
    return;
  end if;

  -- WHY: every decision below is based on this exact row image; the lock makes
  -- a simultaneous draft or verdict wait and re-evaluate after our atomic write.
  select l.*
    into v_row
    from item_ledger as l
    where l.ledger_id = p_ledger_id
    for update;

  if not found then
    return query select false, true, null::numeric, null::numeric, p_ledger_id;
    return;
  end if;

  v_expected_hash := coalesce(
    p_result ->> 'responseHash',
    p_result ->> 'response_hash'
  );
  v_hash_matches := v_expected_hash is not null
    and v_row.frq_response_hash is not distinct from v_expected_hash;
  -- coalesce: a released/reissued claim leaves frq_claim_token NULL or different;
  -- NULL = uuid is SQL-null, and "not null" in the elsif below would silently treat
  -- that as a match-adjacent fallthrough. A worker token matches ONLY a stored equal token.
  v_claim_matches := p_claim_token is not null
    and coalesce(v_row.frq_claim_token = p_claim_token, false);

  if v_row.frq_response_version is distinct from p_response_version then
    return query
      select false, true, v_row.score, v_row.score, v_row.ledger_id;
    return;
  end if;

  if p_claim_token is null then
    -- Teacher/sweep calls have no lease token, so both the explicit authority
    -- bit and caller-carried response hash are mandatory.
    if not coalesce(p_teacher, false) or not v_hash_matches then
      return query
        select false, true, v_row.score, v_row.score, v_row.ledger_id;
      return;
    end if;
  elsif not v_claim_matches then
    -- A non-null worker token must be the token still stored on the row. An
    -- expired-but-unreclaimed owner may finish, but after reclaim the old token
    -- is stale. This intentionally spends one extra model call when a lease
    -- expires mid-grade; accepting a hash plus arbitrary/old token is unsafe.
    return query
      select false, true, v_row.score, v_row.score, v_row.ledger_id;
    return;
  else
    -- The token binds the snapshot. If the caller also carries the hash, reject
    -- disagreement instead of silently trusting one of the two bindings.
    if v_expected_hash is not null and not v_hash_matches then
      return query
        select false, true, v_row.score, v_row.score, v_row.ledger_id;
      return;
    end if;
  end if;

  v_previous_score := v_row.score;
  v_was_appeal := v_row.score is not null and v_row.frq_appeal_pending is not null;
  v_final_score := case
    when v_row.score is null then p_score
    else greatest(v_row.score, p_score)
  end;
  v_applied := v_final_score is distinct from v_row.score
    and v_final_score is not null;

  update item_ledger as l
  set
    score = v_final_score,
    frq_result = case
      when v_applied then
        (
          case when jsonb_typeof(p_result) = 'object' then p_result else '{}'::jsonb end
          - 'responseHash'
          - 'response_hash'
        ) || jsonb_build_object('score', v_final_score)
      else l.frq_result
    end,
    frq_rubric_version = case
      when v_applied then p_rubric_version
      else l.frq_rubric_version
    end,
    graded_at = case
      when v_applied then coalesce(p_graded_at, statement_timestamp())
      else l.graded_at
    end,
    frq_claim_token = null,
    frq_claim_owner = null,
    frq_claimed_until = null,
    frq_retry_count = 0,
    frq_next_attempt_at = null,
    frq_last_error = null,
    -- Preserve the completed request for the student while retaining the hash
    -- and request time used by queue_frq_appeal for dedup and cooldown.
    frq_last_appeal = case
      when v_was_appeal then jsonb_strip_nulls(jsonb_build_object(
        'text', v_row.frq_appeal_pending -> 'text',
        'revisedText', v_row.frq_appeal_pending -> 'revisedText',
        'hash', coalesce(
          v_row.frq_appeal_pending -> 'hash',
          v_row.frq_last_appeal -> 'hash'
        ),
        'at', coalesce(
          v_row.frq_appeal_pending -> 'requestedAt',
          v_row.frq_last_appeal -> 'at',
          to_jsonb(statement_timestamp())
        ),
        'outcome', case when v_applied then 'raised' else 'maintained' end
      ))
      else l.frq_last_appeal
    end,
    frq_appeal_pending = case
      when v_was_appeal then null
      else l.frq_appeal_pending
    end
  where l.ledger_id = p_ledger_id;

  return query
    select v_applied, false, v_previous_score, v_final_score, p_ledger_id;
end;
$$;

-- Release only the lease identified by the caller's token. A reclaimed row has
-- a new token, so a late failure from the old worker cannot erase the new lease.
create or replace function fail_frq_claim(
  p_ledger_id uuid,
  p_claim_token uuid,
  p_error text,
  p_next_attempt_at timestamptz
)
returns boolean
language sql SET search_path TO a2
as $$
  with failure_clock as (
    select statement_timestamp() as at
  ),
  released as (
    update item_ledger as l
    set
      frq_claim_token = null,
      frq_claim_owner = null,
      frq_claimed_until = null,
      frq_retry_count = l.frq_retry_count + 1,
      -- Only operational categories cross this boundary. Provider payloads and
      -- exception text are deliberately collapsed to unknown.
      frq_last_error = case
        when p_error = any (array[
          'timeout',
          'http_4xx',
          'http_5xx',
          'bad_verdict',
          'prompt_error',
          'network',
          'stale',
          'unknown'
        ]::text[]) then p_error
        else 'unknown'
      end,
      frq_next_attempt_at = case
        -- A missing committed rubric cannot heal through model retries. Infinity
        -- keeps the row visible as a durable failed ticket without rescanning it.
        when p_error = 'prompt_error' then 'infinity'::timestamptz
        else least(
          coalesce(p_next_attempt_at, clock.at),
          clock.at + interval '15 minutes'
        )
      end
    from failure_clock as clock
    where l.ledger_id = p_ledger_id
      and l.frq_claim_token = p_claim_token
    returning 1
  )
  select exists(select 1 from released);
$$;

-- Functions are RPCs for the roster service, not public database APIs.
revoke all on function record_frq_draft(uuid, text, text, text, timestamptz) from public;
revoke all on function claim_frq_tickets(text, int, bigint) from public;
revoke all on function apply_frq_verdict(uuid, uuid, bigint, numeric, jsonb, text, timestamptz, boolean) from public;
revoke all on function fail_frq_claim(uuid, uuid, text, timestamptz) from public;
revoke all on function queue_frq_appeal(uuid, text, text, timestamptz, text) from public;

-- Supabase normally provides anon/authenticated/service_role. Local PostgreSQL
-- and differently named platforms may not, so optional role changes are guarded.
-- If service_role is absent, the migration owner retains its normal owner rights
-- and the operator must grant the platform's equivalent service role explicitly.
do $permissions$
declare
  v_role text;
begin
  foreach v_role in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = v_role) then
      execute format(
        'revoke all on function record_frq_draft(uuid, text, text, text, timestamptz) from %I',
        v_role
      );
      execute format(
        'revoke all on function claim_frq_tickets(text, int, bigint) from %I',
        v_role
      );
      execute format(
        'revoke all on function apply_frq_verdict(uuid, uuid, bigint, numeric, jsonb, text, timestamptz, boolean) from %I',
        v_role
      );
      execute format(
        'revoke all on function fail_frq_claim(uuid, uuid, text, timestamptz) from %I',
        v_role
      );
      execute format(
        'revoke all on function queue_frq_appeal(uuid, text, text, timestamptz, text) from %I',
        v_role
      );
    end if;
  end loop;

  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function record_frq_draft(uuid, text, text, text, timestamptz) to service_role';
    execute 'grant execute on function claim_frq_tickets(text, int, bigint) to service_role';
    execute 'grant execute on function apply_frq_verdict(uuid, uuid, bigint, numeric, jsonb, text, timestamptz, boolean) to service_role';
    execute 'grant execute on function fail_frq_claim(uuid, uuid, text, timestamptz) to service_role';
    execute 'grant execute on function queue_frq_appeal(uuid, text, text, timestamptz, text) to service_role';
  end if;
end;
$permissions$;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0031_frq_tickets.sql', '0d2f383dc43982434d9fb0affcb8323af67ba7d860ee120ee88ac9fe9a7a0bf8');
  END IF;
END;
$migration$;

-- 0036_flashcard_state.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0036_flashcard_state.sql' AND digest <> '58966260dfb3a7a5c13d382f35b0ab0b9a58b82a95207e8d435244302c53452e') THEN
    RAISE EXCEPTION 'Applied migration 0036_flashcard_state.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0036_flashcard_state.sql') THEN
-- Fresh-schema replacement for the removed trainer practice-state route.
create table if not exists flashcard_state (
  student_id uuid primary key references roster(student_id) on delete cascade,
  state jsonb not null check (jsonb_typeof(state) = 'object'),
  -- The route caps the UTF-8 request blob at 256 KiB. jsonb::text adds spaces,
  -- so measuring that representation would reject valid boundary-size blobs.
  updated_at timestamptz not null default clock_timestamp()
);

alter table flashcard_state enable row level security;
revoke all on flashcard_state from anon, authenticated;
grant select, insert, update, delete on flashcard_state to service_role;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0036_flashcard_state.sql', '58966260dfb3a7a5c13d382f35b0ab0b9a58b82a95207e8d435244302c53452e');
  END IF;
END;
$migration$;

-- 0037_a2_ledger_sources.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0037_a2_ledger_sources.sql' AND digest <> '8375549d9b6e302779474500370088c329d15e5964ae0c9bd1f648443d0ef6e7') THEN
    RAISE EXCEPTION 'Applied migration 0037_a2_ledger_sources.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0037_a2_ledger_sources.sql') THEN
-- A2 sources use the same ledger, receipt and transcript paths.
alter table item_ledger drop constraint if exists item_ledger_source_check;
alter table item_ledger add constraint item_ledger_source_check
  check (source in ('worksheet','frq','curriculum_quiz','blooket','quiz_exception','quiz_review',
    'lesson-check','try-it','topic-assessment','flashcard'));

-- Atomic best-score preservation for retries using the same ledger attempt.
-- Distinct attempts remain separate evidence; the grade adapter selects their best.
create or replace function preserve_a2_best_score() returns trigger
language plpgsql SET search_path TO a2 as $$
begin
  if (new.source in ('lesson-check', 'topic-assessment', 'flashcard')
      or (new.item_id like 'BL-%-DESK_DONE' and new.source = 'worksheet'))
      and old.score is not null then
    new.score := greatest(old.score, new.score);
  end if;
  return new;
end;
$$;
drop trigger if exists item_ledger_a2_best_score on item_ledger;
create trigger item_ledger_a2_best_score before update on item_ledger
for each row execute function preserve_a2_best_score();
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0037_a2_ledger_sources.sql', '8375549d9b6e302779474500370088c329d15e5964ae0c9bd1f648443d0ef6e7');
  END IF;
END;
$migration$;

-- 0038_a2_lessons.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0038_a2_lessons.sql' AND digest <> '645fe2b059c4f24c56617ba68b692913470869f1d0feaa81ad29e0b3d431679d') THEN
    RAISE EXCEPTION 'Applied migration 0038_a2_lessons.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0038_a2_lessons.sql') THEN
create table if not exists a2_lesson_pacing (
  lesson text primary key,
  sections jsonb,
  onenote_url text
);
create table if not exists a2_rescore_requests (
  student_id uuid references roster(student_id) on delete cascade,
  item_id text not null,
  requested_at timestamptz not null default now(),
  primary key (student_id, item_id)
);
alter table a2_lesson_pacing enable row level security;
alter table a2_rescore_requests enable row level security;
revoke all on a2_lesson_pacing, a2_rescore_requests from anon, authenticated;
grant all on a2_lesson_pacing, a2_rescore_requests to service_role;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0038_a2_lessons.sql', '645fe2b059c4f24c56617ba68b692913470869f1d0feaa81ad29e0b3d431679d');
  END IF;
END;
$migration$;

-- 0039_announcements.sql
DO $migration$
BEGIN
  IF EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0039_announcements.sql' AND digest <> '9e34eac66690adaa2a6ca0743119d0e5053cbb5d3a02449cad8ee0377bf888cb') THEN
    RAISE EXCEPTION 'Applied migration 0039_announcements.sql changed; author a new migration instead';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM a2._bootstrap_migrations WHERE name = '0039_announcements.sql') THEN
create table if not exists announcements (
  week_of date primary key,
  text text not null,
  updated_at timestamptz not null,
  updated_by text
);
alter table announcements enable row level security;
revoke all on announcements from anon, authenticated;
grant all on announcements to service_role;
    INSERT INTO a2._bootstrap_migrations(name, digest) VALUES ('0039_announcements.sql', '9e34eac66690adaa2a6ca0743119d0e5053cbb5d3a02449cad8ee0377bf888cb');
  END IF;
END;
$migration$;

-- Tables, views and RPCs belong to a2. Only the server role may use them.
REVOKE ALL ON ALL TABLES IN SCHEMA a2 FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA a2 FROM anon, authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA a2 FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA a2 TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA a2 TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA a2 TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA a2 TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA a2 GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA a2 GRANT ALL ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA a2 GRANT EXECUTE ON FUNCTIONS TO service_role;
-- PostgreSQL's built-in PUBLIC function grant cannot be removed per schema
-- with default privileges. Future migrations must explicitly revoke it too.
NOTIFY pgrst, 'reload schema';
COMMIT;
